### ISSUE TITLE
 جهانڭيرى  and jahāngīrī

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ArabicInSanskrit#11]
@jlreeder 

Hi, Jason.

In working with corrections for mw72,  we came upon:
```
78314 new <P>.{#jAMhagiri#}¦ {%jāṉhagiri, is,%} m. {%= jahāngīrī.%}
```
We  were questioning whether that last word (`jahāngīrī`) is a Sanskrit word.

A search of  PWG under headword [jAMhagiri](http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2013/web/webtc/indexcaller.php?key=jAMhagiri), shows
some Arabic text.

Question 1:  This leads me to believe that jahāngīrī is in fact a European spelling of an Arabic word.
      Do you agree?

When the Arabic script is copy/pasted into Google Translate,  there is an oddity:

![image](https://cloud.githubusercontent.com/assets/6393033/20818420/78ca0a44-b7fb-11e6-812a-956c8d2d1a24.png)

Question 2:  Any idea why part of the Arabic script appears in the English translation?

**Comment by jsonreeder** [comment]
Very cool word! I've done some snooping, and here's what I've found. 

__Question 1__: Origin
It appears to be of Persian origin. I recognized it as a district of Istanbul, which is Romanized in Modern Turkish to Cihangir (though <c> is pronounced [dj]). That Wikipedia page ([link](https://en.wikipedia.org/wiki/Cihangir)) cites the origin of the name as Persian:
> The name means "conqueror" in Turkish and, in turn, comes from the Persian compound word jahan + gir (جهانگیر), meaning "conqueror of the world".

I don't mean to suggest that this Sanskrit word has anything to do with Istanbul, but it seems likely that the neighborhood and the Sanskrit word share a common Persian Root.

The "i" at the end of the Sanskrit derivative "jāṁhagiri" could be from a few sources. It could be a demonym, as in "someone from a town called Jamhangir" or a patronymic, "someone related to a person named Jamhangir." It could also be a Sanskrit morpheme of course, though I would not be able to tell you which one. As far as I'm concerned it's a common enough particle that we can consider it "additional" and that the core of the word's origin is "jahan" + "gir."

__Question 2__: ڭ

The character is not showing up in the translation for two reasons:
- It is not used in Arabic at all
- Strictly speaking it is not used in modern Farsi either. It has been replaced by the related گ (a line ـگـ instead of three dots ـڭـ). As far as I understand they are both equivalent to the English voiced velar stop [g]. Note that the etymology taken above from wikipedia uses the later character.
- You may wonder whether the initial character should be replaced in the digitized dictionary. This would be reasonable, but if I remember correctly there was a decision made to stay as close to the original characters used in the printed edition as possible. Personally I don't know enough about Persian/Farsi to know for certain whether the two characters are actually identical, so I'd lean towards keeping the character from the original dictionary.

**Comment by funderburkjim** [comment]
Pasting the Arabic script into Google Translate with PERSIAN,  there is no Unknown letter. and the English response shows Jhanngyry.   Another confirm of your analysis!

Incidentally, the 'giri' part is a common Sanskrit word, meaning mountain, and MW shows Zend 'gaira' as a related word, and Zend seems to be related to Persian.

Very interesting.

Thanks for the lesson!

**Comment by drdhaval2785** [comment]
It is dIrgha I ई, not i इ.

This suffix is applied to denote relatedness.
Not related to giri mountain.

**Comment by funderburkjim** [comment]
is that 'gIr'/'gIri'  'suffix .. relatedness' used in some modern Indian language ? --- I can't find it in Sanskrit.

**Comment by gasyoun** [comment]
> a decision made to stay as close to the original characters used in the printed edition as possible

Indeed.

> Zend seems to be related to Persian.

Sure it is, it's an earlier stage of the language. Old Persian -> Middle (Farsi, for example) - > Persian.

**Comment by ghost** [comment]
> is that 'gIr'/'gIri' 'suffix .. relatedness' used in some modern Indian language ? --- I can't find it in Sanskrit.

-gar is a Persian suffix equivalent to English -er
See the 3rd etymology here https://en.wiktionary.org/wiki/%DA%AF%D8%B1.

From an Urdu - English dictionary (Duncan Forbes, _A Hindustani-English Dictionary_):
گر gar (in composition) a maker or a workman, as _zar-gar_, a worker in gold, a goldsmith. [...] 

Two common Hindi words are जादूगर (which is the standard word for 'magician') and  बाज़ीगर. I am unable to think of more words with the -gar suffix right now, but the meaning is certainly obviously.

The -i suffix (an drdhaval said above) would add a relatedness meaning to the word. So, जादूगरी means the process of doing जादू (magic, Farsi), the work of a जादूगर, etc. (This too is a common word.)

जादूगरी: https://dsalsrv04.uchicago.edu/cgi-bin/app/dasa-hindi_query.py?qs=%E0%A4%9C%E0%A4%BE%E0%A4%A6%E0%A5%82%E0%A4%97%E0%A4%B0%E0%A5%80&searchhws=yes

The above may not illuminate anything about the MW72 or PWG entries, but it answers your question!

Edit: Forgot to add, this गर has nothing to do with the गीर in जहाँगीर. From Forbes’ dictionary again,

[] _gīr_, (in composition) taking, seizing, holding; as _’ālam-gīr_ or _jahān-gīr_, seizing or conquering the world _persian_.

**Comment by gasyoun** [comment]
> The above may not illuminate anything about the MW72 or PWG entries, but it answers your question!

A good one, keep on.
